// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXkTUgQy4mfOKI5WDG5OL0K8SJDqrVfI',
    appId: '1:808314993567:web:1aa2f7db3cca1b2bc79baa',
    messagingSenderId: '808314993567',
    projectId: 'globachat-2024',
    authDomain: 'globachat-2024.firebaseapp.com',
    databaseURL: 'https://globachat-2024-default-rtdb.firebaseio.com',
    storageBucket: 'globachat-2024.firebasestorage.app',
    measurementId: 'G-CP4M6PC90Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr7rUNpjinOpcP2B-E0r09bGX-q39zCsY',
    appId: '1:808314993567:android:120976f5c5b7b213c79baa',
    messagingSenderId: '808314993567',
    projectId: 'globachat-2024',
    databaseURL: 'https://globachat-2024-default-rtdb.firebaseio.com',
    storageBucket: 'globachat-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6kZvXYyHW2vaZe9zRqSbvkBYxnEzeMc0',
    appId: '1:808314993567:ios:22092e25fc2098b1c79baa',
    messagingSenderId: '808314993567',
    projectId: 'globachat-2024',
    databaseURL: 'https://globachat-2024-default-rtdb.firebaseio.com',
    storageBucket: 'globachat-2024.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6kZvXYyHW2vaZe9zRqSbvkBYxnEzeMc0',
    appId: '1:808314993567:ios:22092e25fc2098b1c79baa',
    messagingSenderId: '808314993567',
    projectId: 'globachat-2024',
    databaseURL: 'https://globachat-2024-default-rtdb.firebaseio.com',
    storageBucket: 'globachat-2024.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCXkTUgQy4mfOKI5WDG5OL0K8SJDqrVfI',
    appId: '1:808314993567:web:a1a09366245c4fb8c79baa',
    messagingSenderId: '808314993567',
    projectId: 'globachat-2024',
    authDomain: 'globachat-2024.firebaseapp.com',
    databaseURL: 'https://globachat-2024-default-rtdb.firebaseio.com',
    storageBucket: 'globachat-2024.firebasestorage.app',
    measurementId: 'G-5NC4FQV86V',
  );

}