name: chat
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  cupertino_icons: ^1.0.8
  firebase_database: ^10.5.7
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.12
  permission_handler: ^11.4.0
  pin_code_fields: ^8.0.1
  get: ^4.7.2
  vibration: ^3.1.3
  floor: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true