// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA16E0F-kU48WJTSuXh1oe2Lh6r7sG2LEc',
    appId: '1:498243208924:web:99d56a493474fdad219619',
    messagingSenderId: '498243208924',
    projectId: 'chatfy-global',
    authDomain: 'chatfy-global.firebaseapp.com',
    storageBucket: 'chatfy-global.firebasestorage.app',
    measurementId: 'G-EBX3FYTBR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6e-e1kz9Nsnscaj0E12aLETyIQHHqHmk',
    appId: '1:498243208924:android:fcef4fb7414b7a0c219619',
    messagingSenderId: '498243208924',
    projectId: 'chatfy-global',
    storageBucket: 'chatfy-global.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKHv74pHLI_HEsWh6R-w3fM4QP5GjgsQg',
    appId: '1:498243208924:ios:ec54a5357c9a7bfa219619',
    messagingSenderId: '498243208924',
    projectId: 'chatfy-global',
    storageBucket: 'chatfy-global.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKHv74pHLI_HEsWh6R-w3fM4QP5GjgsQg',
    appId: '1:498243208924:ios:ec54a5357c9a7bfa219619',
    messagingSenderId: '498243208924',
    projectId: 'chatfy-global',
    storageBucket: 'chatfy-global.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA16E0F-kU48WJTSuXh1oe2Lh6r7sG2LEc',
    appId: '1:498243208924:web:bdc2164f32895a46219619',
    messagingSenderId: '498243208924',
    projectId: 'chatfy-global',
    authDomain: 'chatfy-global.firebaseapp.com',
    storageBucket: 'chatfy-global.firebasestorage.app',
    measurementId: 'G-S58Z2C38PG',
  );
}
